name: Build Eron OS ISO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            gcc-multilib \
            grub-pc-bin \
            grub-common \
            xorriso \
            mtools

      - name: Build do Eron
        run: |
          make clean || true
          make

      - name: Verificar binario
        run: |
          file eron.bin
          ls -lah eron.iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: eron-iso
          path: eron.iso
